org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
group_id=com.momosoftworks
mod_name=ColdSweat
mc_version=1.18.2
mod_version=2.4-b06g

valk_skies_api_version=1.1.0+2a62e6a823
valk_skies_main_version=2.1.1-beta.6+a0517bae1e
rhino_version = 1802.1.13-build.175
architectury_version=4.1.36
jei_version=10.2.1.1009